# Generated by Django 5.0.3 on 2024-03-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip", models.GenericIPAddressField()),
                ("browser", models.CharField(max_length=200)),
                ("click_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
